# Fuzzy-Rough Sets

Let $U$ represent the universe of discourse, $X \in U$ a fuzzy set and $R \in \mathcal{F}(U \times U)$ a fuzzy binary relation, such that $\mu_X(x)$ and $\mu_R(y,x)$ are their respective membership functions. The memership function $\mu_X : U \rightarrow [0,1]$ determines the degree to which $x \in U$ is a member of $X$, whereas $\mu_R: U \times U \rightarrow [0,1]$ denotes the degree to which $y$ is presumed to be a member of $X$ from the fact that $x$ is a member of the fuzzy set $X$. Whenever deemed opportune, and if not confusion arises, we will denote $R(x)$ with its membership function $\mu_{R(x)}(y)=\mu_R(y,x)$.


### Step 1. Create a partition based on the decision class
Firstly, let us build a partition of $U$ according to the decision classes. The $X_k$ set contains all objects associated with the $k$-th decision class. In previous research works, the membership degree of $x \in U$ to a subset $X_k$ was computed using the following hard membership function:

$\mu_{X_k}(x) = \left \{ \begin{matrix} 1 & \mbox{ , } x \in X_k \\
		 0 & \mbox{ , } x \notin X_k \end{matrix} \right.$


<div style="width:image width px;
            font-size:80%; 
            text-align:center; 
            float: right; padding-left-right-top-bottom:0.5em;  
            border-style: solid; border-color: rgba(211, 211, 211, 0.1);
            background-color: rgba(240, 240, 240, 0.1);">
    <img src="https://i.imgur.com/YqqA2lv.png" 
         alt="alternate text" 
         width=250 
         style="padding-bottom:0.5em;"/>
    <div style="padding: 3px; 
                width: 250px; 
                word-wrap: break-word; 
                text-align:justify;">
    </div>
</div>

### Step 2. Compute the similarity between instances

The similarity between two objects $x \in U$ and $y \in U$ can be computed as follows:

$\varphi(x,y) = e^{-\alpha d(x,y)}$

where $d(x,y)$ computes the Manhattan or Euclidean distance. The exponential function returns values in the $(0,1]$ interval when fed with negative values. This means that a strict normalization is not required. However, we need to tune the $\lambda > 0$ parameter such that we can have more separable regions.

Next, we can compute the fuzzy binary relation $\mu_R(y,x)$ as follows:
    
$\mu_R(y,x) = \mu_{X_k}(x)\varphi(x,y).$

### Step 3. Compute the lower and upper approximations

To define the lower approximations, we use the degree of $x$ being a member of $X_k$ under the knowledge $R$. This can be measured by the truth value of the statement "$y \in R(x)$ implies $y \in X_k$" under fuzzy sets $R(x)$ and $X_k$. We use a necessity measure $\inf_{y \in U} \mathcal{I}(\mu_R(y,x), \mu_{X_k}(y))$ with a fuzzy implication function $\mathcal{I}:[0,1] \times [0,1] \rightarrow [0,1]$ such that $\mathcal{I}(0,0) = \mathcal{I}(0,1) = \mathcal{I}(1, 1) = 0$ and $\mathcal{I}(1, 0) = 1$. Furthermore, $\mathcal{I}(.,a)$ decreases and $\mathcal{I}(a,.)$ increases, $\forall a \in [0,1]$. Recall that $X_k$ is the set of objects labeled with the $k$-th decision class. The following equation displays the membership function for the lower approximation $R_*(X_k)$ associated with the $k$-th decision class,

$\mu_{R_*(X_k)}(x) = \min \left\lbrace \mu_{X_k}(x), \inf_{y \in U} \mathcal{I}(\mu_R(y,x), \mu_{X_k}(y)) \right\rbrace$ where $\mathcal{I}(a,b) = \min(1 - a + b, 1)$ is the Łukasiewicz implication operator.

To derive the upper approximations, we should measure the truth value of the statement "$\exists y \in U$ such that $x \in R(y)$" under fuzzy sets $R(x)$ and $X_k$. The true value of this statement can be obtained by a possibility measure $\sup_{y \in U} \mathcal{T}(\mu_R(x,y), \mu_{X_k}(y))$ with a conjunction function $\mathcal{T}:[0,1] \times [0,1] \rightarrow [0,1]$ such that such that $\mathcal{T}(0,0) = \mathcal{T}(0,1) = \mathcal{T}(1,1)= 1$ and $\mathcal{T}(1,0) = 0$, where both $\mathcal{T}(.,a)$  and $\mathcal{T}(a,.)$ increase, $\forall a \in [0,1]$. The following equation shows the membership function for the upper approximation $R^*(X_k)$ associated with the $k$-th decision class,

$\mu_{R^*(X_k)}(x) = \max \left\lbrace \mu_{X_k}(x), \sup_{y \in U} \mathcal{T}(\mu_R(x,y), \mu_{X_k}(y)) \right\rbrace$ where $\mathcal{T}(a,b) = \max(a + b - 1, 0)$ is the Łukasiewicz conjunction operator.

This model does not assume that $\mu_R(x,x)=1, \forall x \in U$. Instead, we compute the minimum between $\mu_{X_k}(x)$ and $\inf_{y \in U} \mathcal{I}(\mu_R(y,x), \mu_{X_k}(y))$ when calculating $\mu_{R_*(X_k)}(x)$, and the maximum between $\mu_{X_k}(x)$ and $\sup_{y \in U} \mathcal{T}(\mu_R(x,y), \mu_{X_k}(y))$ when calculating $\mu_{R^*(X_k)}(x)$. This allows preserving the inclusiveness of $R_*(X_k)$ in the fuzzy set $X_k$ and the inclusiveness of $X_k$ in $R^*(X_k)$.

### Step 4. Compute the positive, boundary and negative regions

Based on the above elements, one can define the three fuzzy-rough regions that comprise the granulation stage's core. The following equations display the membership functions associated with the fuzzy-rough positive, negative and boundary regions, respectively,

$\mu_{POS(X_k)}(x) = \mu_{R_*(X_k)}(x)$, $\mu_{NEG(X_k)}(x) = 1-\mu_{R^*(X_k)}(x)$ and $\mu_{BND(X_k)}(x) = \mu_{R^*(X_k)}(x)-\mu_{R_*(X_k)}(x)$.

These memberships functions allow computing more flexible information granules describing the problem. Consequently, abrupt transitions between decision classes are replaced with gradual ones, thus allowing an element to belong to more than one class with varying degrees.

In [32]:
import numpy as np
import pandas as pd
import time
from csv import writer
from Preprocess_data import preprocess_datasets

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics.pairwise import euclidean_distances

In [68]:
dataset = 'german.data' # 'synthetic.csv', 'BROWARD_CLEAN.csv, 'titanic.csv', 'adult.data'
df = preprocess_datasets(dataset).preprocess_dataset()
df.head()

,Status_of_existing_checking_account,Duration_in_month,Credit_history,Purpose,Credit_amount,Savings_accountbonds,Present_employment_since,Installment_rate_in_percentage_of_disposable_income,Personal_status_and_sex,Other_debtorsguarantors,...,Property,Age_in_years,Other_installment_plans,Housing,Number_of_existing_credits_at_this_bank,Job,Number_of_people_being_liable_to_provide_maintenance_for,Telephone,Foreign_worker,Creditworthiness
0,A11,0.029412,A34,A43,0.050567,A65,A75,1.000000,male,A101,...,A121,0.857143,A143,A152,0.333333,A173,0.0,A192,A201,1
1,A14,0.117647,A34,A46,0.101574,A61,A74,0.333333,male,A101,...,A121,0.535714,A143,A152,0.000000,A172,1.0,A191,A201,1
2,A11,0.558824,A32,A42,0.419941,A61,A74,0.333333,male,A103,...,A122,0.464286,A143,A153,0.000000,A173,1.0,A191,A201,1
3,A14,0.470588,A32,A46,0.484483,A65,A73,0.333333,male,A101,...,A124,0.285714,A143,A153,0.000000,A172,1.0,A192,A201,1
4,A14,0.294118,A32,A42,0.142236,A63,A75,0.666667,male,A101,...,A122,0.607143,A143,A152,0.000000,A173,0.0,A191,A201,1

In [74]:
class FRS:

    def __init__(self, df, features=None, alpha=1.0, distance = 'HEOM'):
        
        self.alpha = alpha
        self.features = features
        self.data, self.target, self.membership, self.numeric, self.nominal = self.preprocess(df)
        self.distance = distance
        
    def preprocess(self, df):

        df_new = df.copy()
        target = df_new.pop(df_new.columns[-1])
        target = LabelEncoder().fit(target).transform(target)
        membership = pd.get_dummies(target)
        numeric = [False if df_new[col].dtype == 'object' else True for col in df_new]
        nominal = [True if df_new[col].dtype == 'object' else False for col in df_new]

        return df_new.to_numpy(), target, membership.to_numpy(), numeric, nominal

    def regions(self):

        POS = np.zeros((len(np.unique(self.target)), len(self.data)))
        NEG = np.zeros((len(np.unique(self.target)), len(self.data)))
        BND = np.zeros((len(np.unique(self.target)), len(self.data)))
        
        for i in range(len(self.data)):
            distance = self.similarity(i) 
            for k in np.unique(self.target):
                POS[k][i], NEG[k][i], BND[k][i] = self.process_object(i, k, distance)

        return [POS, NEG, BND]

    def similarity(self, i):
        
        if self.distance == 'HEOM':
            d = np.sum(
                np.abs(
                    np.subtract(self.data[i,self.numeric].T.values,self.data[:,self.numeric])),
                    axis=1) + np.sum(self.Z.loc[i,self.nominal].T != self.Z.loc[:,self.nominal],axis=1)
        if self.distance == 'HMOM':
            d = np.sum(
                np.subtract(self.data[i,self.numeric].T,self.data[:,self.numeric])**2,
                        axis=1) + np.sum(self.data[i,self.nominal].T != self.data[:,self.nominal],axis=1)
        
        return np.exp(-self.alpha * d.astype('float64'))

    def process_object(self, i, k, distance):

        fuzzy_relation_i_j = distance * self.membership[i,k]
        
        fuzzy_implication = self.implicator(fuzzy_relation_i_j, self.membership[:,k])
        infinum = min(1, fuzzy_implication)
        inf = min(infinum, self.membership[i,k])
        
        if self.membership[i,k] == 0.0:
          fuzzy_relation_j_i = distance * 1.0
        else:
          fuzzy_relation_j_i = distance * 0.0
        fuzzy_conjunction = self.conjunction(fuzzy_relation_j_i, self.membership[:,k])
        supremum = max(0, fuzzy_conjunction)
        sup = max(supremum, self.membership[i,k])

        return inf, 1-sup, sup-inf

    def implicator(self, a, b):
        return min(np.min(1 - a + b), 1)

    def conjunction(self, a, b):
        return max(np.max(a + b - 1), 0)

In [14]:
def uncertainty(full, prot, decision_class):
    '''
    Parameters
    ----------
    full: membership values of instances to the boundary regions using the full set of features,
    prot: membership values of instances to the boundary regions using the set of features without including the protected feature
    decision_class: index of the decision class
    Returns
    -------
    FRU-value attached to the specified decision class for the protected attribute that was removed
    '''
    
    POS_full, NEG_full, BND_full = full
    POS_prot, NEG_prot, BND_prot = prot

    diff_prot = BND_prot[decision_class] - BND_full[decision_class]
    diff_prot = np.where(diff_prot < 0, 0, diff_prot)
    from numpy import linalg as la

    return round((float(la.norm(diff_prot) / la.norm(BND_full[decision_class]))),2)

In [73]:
full = FRS(df, alpha=0.5, distance = 'HMOM').regions()
for col in df.columns[:-1]:
  co=list(df.columns)
  co.remove(col)
  prot = FRS(df[co], alpha=0.5, distance = 'Manhattan').regions()

  res = [col, 'FRU class 1:',uncertainty(full, prot, 0),'FRU class 2:',uncertainty(full, prot, 1)]
  print(res)

  with open("results.csv", 'a') as f:
      csv_writer = writer(f, lineterminator='\n')
      csv_writer.writerow(res)

['Status_of_existing_checking_account', 'class 1:', 0.38, 'class 2:', 0.38]
['Duration_in_month', 'class 1:', 0.05, 'class 2:', 0.05]
['Credit_history', 'class 1:', 0.27, 'class 2:', 0.27]
['Purpose', 'class 1:', 0.37, 'class 2:', 0.37]
['Credit_amount', 'class 1:', 0.03, 'class 2:', 0.03]
['Savings_accountbonds', 'class 1:', 0.31, 'class 2:', 0.31]
['Present_employment_since', 'class 1:', 0.36, 'class 2:', 0.36]
['Installment_rate_in_percentage_of_disposable_income', 'class 1:', 0.14, 'class 2:', 0.14]
['Personal_status_and_sex', 'class 1:', 0.23, 'class 2:', 0.23]
['Other_debtorsguarantors', 'class 1:', 0.15, 'class 2:', 0.15]
['Present_residence_since', 'class 1:', 0.14, 'class 2:', 0.14]
['Property', 'class 1:', 0.32, 'class 2:', 0.32]
['Age_in_years', 'class 1:', 0.05, 'class 2:', 0.05]
['Other_installment_plans', 'class 1:', 0.23, 'class 2:', 0.23]
['Housing', 'class 1:', 0.18, 'class 2:', 0.18]
['Number_of_existing_credits_at_this_bank', 'class 1:', 0.04, 'class 2:', 0.04]
['Job', 'class 1:', 0.23, 'class 2:', 0.23]
['Number_of_people_being_liable_to_provide_maintenance_for', 'class 1:', 0.14, 'class 2:', 0.14]
['Telephone', 'class 1:', 0.22, 'class 2:', 0.22]
['Foreign_worker', 'class 1:', 0.08, 'class 2:', 0.08]